### ISSUE TITLE
Remove duplicate entries in list of municipality

### ISSUE THREAD

**Issue by BraveheartWikimedia** [Wikimedia-Austria/WikiDaheim#112]
Hi Bene!

We currently have the issue that some Wikidata entries are shown twice if they have two or more coordinates in the Wikidata item. One example is the "Further Bach" in Furth an der Triesting. According to @pixelhaufen this needs to be solved in the interface. I don't think it matters much which entry disappears. 

BR,
Philip

**Comment by reiterbene** [comment]
will take a look!

**Comment by reiterbene** [comment]
I do not see any duplicate entries in Furth an der Triesting regarding "Further Bach". Has there been a change on the server side in the meantime?

**Comment by BraveheartWikimedia** [comment]
@pixelhaufen Did you change anything on the server side? I can't find the second entry either.

**Comment by pixelhaufen** [comment]
Maybe they are gone because somebody asked me to reset the code to not show any duplicate entries? https://de.wikipedia.org/w/index.php?title=Wikipedia_Diskussion:WikiDaheim&diff=213880800&oldid=prev I can enable it again, however the database might need some hours to get the entries. Just let me know what you want...

**Comment by BraveheartWikimedia** [comment]
Ok, thanks, I think we can leave it at that then :-)
