### ISSUE TITLE
Bilderwunsch filfilled, but still shown in app (different from #188)

### ISSUE THREAD

**Issue by HerziPinki** [Wikimedia-Austria/WikiDaheim#189]
In https://de.wikipedia.org/wiki/Liste_der_Hospize_in_der_Steiermark there are some explicit Bilderwünsche. While BW in https://wikidaheim.at/Q608977 (Friedberg) is ok, BW in https://wikidaheim.at/Q673333 (Pöllau) is not.

On the other hand. BW in https://wikidaheim.at/Q661519 (Frohnleiten) for 'Volkshilfe Seniorenzentrum Frohnleiten' is no longer shown, which is correct.

BW is related to a single table row with native table syntax (no template). 

Is there an update problem? Or something else.

**Comment by pixelhaufen** [comment]
Hope @simon04 can help. The data is from [bldrwnsch .json](https://tools.wmflabs.org/bldrwnsch/Bilderwuensche.json). Is there a problem with the .json? The [map](https://bldrwnsch.toolforge.org/) seems to be ok.

**Comment by simon04** [comment]
Hi @pixelhaufen, due to Toolserver changes https://phabricator.wikimedia.org/T319593, I had to re-implement the entire processing of Bilderwünsche in https://github.com/simon04/bldrwnsch/commit/1e9234db8f1d4f57b0b7734e887144270feb39eb. The JSON file is no longer being generated. Can you make use of the GeoJSON file https://bldrwnsch.toolforge.org/Bilderwuensche.geojson instead? Thanks!

**Comment by simon04** [comment]
Good point, done in https://github.com/simon04/bldrwnsch/commit/e7f1ec93509cbf14b4a60fb1b8093ddd18addc42. Glad to hear that you could update your scripts. :-)
